### PR TITLE
fixes for public header inclusion

### PR DESCRIPTION
**Pull request by sezero**
@madebr, @icculus, and @slouken: Please review.

@madebr: I think VisualC/pkg-support/cmake part needs to be done for all
other satellite libs _and_ SDL3 itself. Correct?

### CODE REVIEW

**Review by madebr — APPROVED** [review]
Indeed, the pkg-support cmake files of all other libraries don't have this yet.

**Comment by sezero** [comment]
OK pulled this in.

**Comment by sezero** [comment]
And applied and pushed VisualC/pkg-support/cmake change to all SDL projects and SDL itself. (Please confirm when you can.)

**Comment by madebr** [comment]
> And applied and pushed VisualC/pkg-support/cmake change to all SDL projects and SDL itself. (Please confirm when you can.)

They look fine to me. The xcode projects will also need changes (that should simplify them).

**Comment by sezero** [comment]
> > And applied and pushed VisualC/pkg-support/cmake change to all SDL projects and SDL itself. (Please confirm when you can.)
> 
> They look fine to me.

OK

> The xcode cmake pkg-support files will also need changes (that should simplify them).

Can I leave that you?

**Comment by madebr** [comment]
> Can I leave that you?

**Pull request merged**
