### PR TITLE
CMake support

### PR DESCRIPTION
**Pull request by FtZPetruska**
## Description

* Adding a basic CMake support
* Based on SDL_ttf's implementation
* Exports the libraries in the SDL2_net namespace
* Option to build showinterfaces (off by default)
* Tested on Windows 10, WSL2 and macOS (x64 only)
* Works with SDL2 2.0.10 and above (relies on SDL2 namespace being available)
* Additionally, the existing .hgignore was moved into a .gitignore and platform-specific rules were added.

## Existing Issue

#33

### CODE REVIEW

**Comment by FtZPetruska** [comment]
Before merging, I wanted to mention that I was not sure if the INTERFACE_AGE and BINARY_AGE have the correct value.
Currently they are set as such:
```cmake
  set(SDL_NET_INTERFACE_AGE 1)
  set(SDL_NET_BINARY_AGE 1)
```

**Comment by slouken** [comment]
Why was this closed?

**Comment by FtZPetruska** [comment]
I was cleaning some forks I had on my account and I guess it closed it.

Although looking back at it, it would have needed more changes and would conflict with the newly added workflows.

Apologies for the inconvenience.

**Comment by slouken** [comment]
Okay, feel free to reopen and update if desired.

**Pull request closed without merging**
